(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l="Symbol.iterator",p="function",q="object",r="string",t,u=typeof Object.defineProperties==p?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=[q==typeof globalThis&&globalThis,a,q==typeof window&&window,q==typeof self&&self,q==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ba=aa(this),v=function(a,b){if(b)a:{var c=ba;a=a.split(".");
for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&u(c,a,{configurable:!0,writable:!0,value:b})}},w=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},x=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:w(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};
v("Symbol",function(a){if(a)return a;var b=function(h,m){this.ba=h;u(this,"description",{configurable:!0,writable:!0,value:m})};b.prototype.toString=function(){return this.ba};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(h){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(h||"")+"_"+d++,h)};return e},"es6","es3");
v(l,function(a){if(a)return a;a=Symbol(l);u(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return y(w(this))}});return a},"es6","es3");var y=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},A=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
v("WeakMap",function(a){function b(){}function c(g){var k=typeof g;return k===q&&g!==null||k===p}function d(g){if(!A(g,h)){var k=new b;u(g,h,{value:k})}}function e(g){var k=Object[g];k&&(Object[g]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return k(n)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),n=new a([[g,2],[k,3]]);if(n.get(g)!=2||n.get(k)!=3)return!1;n.delete(g);n.set(k,4);return!n.has(g)&&n.get(k)==4}catch(z){return!1}}())return a;
var h="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var m=0,f=function(g){this.I=(m+=Math.random()+1).toString();if(g){g=x(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}};f.prototype.set=function(g,k){if(!c(g))throw Error("Invalid WeakMap key");d(g);if(!A(g,h))throw Error("WeakMap key fail: "+g);g[h][this.I]=k;return this};f.prototype.get=function(g){return c(g)&&A(g,h)?g[h][this.I]:void 0};f.prototype.has=function(g){return c(g)&&A(g,h)&&A(g[h],this.I)};
f.prototype.delete=function(g){return c(g)&&A(g,h)&&A(g[h],this.I)?delete g[h][this.I]:!1};return f},"es6","es3");
v("Map",function(a){if(function(){if(!a||typeof a!=p||!a.prototype.entries||typeof Object.seal!=p)return!1;try{var f=Object.seal({x:4}),g=new a(x([[f,"s"]]));if(g.get(f)!="s"||g.size!=1||g.get({x:4})||g.set({x:4},"t")!=g||g.size!=2)return!1;var k=g.entries(),n=k.next();if(n.done||n.value[0]!=f||n.value[1]!="s")return!1;n=k.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!k.next().done?!1:!0}catch(z){return!1}}())return a;var b=new WeakMap,c=function(f){this[0]={};this[1]=h();this.size=0;if(f){f=
x(f);for(var g;!(g=f.next()).done;)g=g.value,this.set(g[0],g[1])}};c.prototype.set=function(f,g){f=f===0?0:f;var k=d(this,f);k.list||(k.list=this[0][k.id]=[]);k.entry?k.entry.value=g:(k.entry={next:this[1],u:this[1].u,head:this[1],key:f,value:g},k.list.push(k.entry),this[1].u.next=k.entry,this[1].u=k.entry,this.size++);return this};c.prototype.delete=function(f){f=d(this,f);return f.entry&&f.list?(f.list.splice(f.index,1),f.list.length||delete this[0][f.id],f.entry.u.next=f.entry.next,f.entry.next.u=
f.entry.u,f.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].u=h();this.size=0};c.prototype.has=function(f){return!!d(this,f).entry};c.prototype.get=function(f){return(f=d(this,f).entry)&&f.value};c.prototype.entries=function(){return e(this,function(f){return[f.key,f.value]})};c.prototype.keys=function(){return e(this,function(f){return f.key})};c.prototype.values=function(){return e(this,function(f){return f.value})};c.prototype.forEach=function(f,g){for(var k=
this.entries(),n;!(n=k.next()).done;)n=n.value,f.call(g,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(f,g){var k=g&&typeof g;k==q||k==p?b.has(g)?k=b.get(g):(k=""+ ++m,b.set(g,k)):k="p_"+g;var n=f[0][k];if(n&&A(f[0],k))for(f=0;f<n.length;f++){var z=n[f];if(g!==g&&z.key!==z.key||g===z.key)return{id:k,list:n,index:f,entry:z}}return{id:k,list:n,index:-1,entry:void 0}},e=function(f,g){var k=f[1];return y(function(){if(k){for(;k.head!=f[1];)k=k.u;for(;k.next!=k.head;)return k=
k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})},h=function(){var f={};return f.u=f.next=f.head=f},m=0;return c},"es6","es3");var B=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};v("Array.prototype.keys",function(a){return a?a:function(){return B(this,function(b){return b})}},"es6","es3");
v("Array.prototype.values",function(a){return a?a:function(){return B(this,function(b,c){return c})}},"es8","es3");v("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(f){return f};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h==p){b=h.call(b);for(var m=0;!(h=b.next()).done;)e.push(c.call(d,h.value,m++))}else for(h=b.length,m=0;m<h;m++)e.push(c.call(d,b[m],m));return e}},"es6","es3");var C=this||self,D=function(a){var b=typeof a;b=b!=q?b:a?Array.isArray(a)?"array":b:"null";return b=="array"||b==q&&typeof a.length=="number"};var E,F;a:{for(var G=["CLOSURE_FLAGS"],H=C,I=0;I<G.length;I++)if(H=H[G[I]],H==null){F=null;break a}F=H}var J=F&&F[610401301];E=J!=null?J:!1;var K,L=C.navigator;K=L?L.userAgentData||null:null;function M(a){if(!E||!K)return!1;for(var b=0;b<K.brands.length;b++){var c=K.brands[b].brand;if(c&&c.indexOf(a)!=-1)return!0}return!1}function N(a){var b;a:{if(b=C.navigator)if(b=b.userAgent)break a;b=""}return b.indexOf(a)!=-1};function O(a){return a!==void 0&&a||E?!!K&&K.brands.length>0:!1};var ca=O()?!1:N("Trident")||N("MSIE");var P=function(a,b){return typeof b===r?a.getElementById(b):b},Q=function(a,b,c,d){a=d||a;return(b=b&&b!="*"?String(b).toUpperCase():"")||c?a.querySelectorAll(b+(c?"."+c:"")):a.getElementsByTagName("*")};function R(a){this.K=a}R.prototype.ja=function(a){var b=[];this.O(a,b);return b.join("")};
R.prototype.O=function(a,b){if(a==null)b.push("null");else{if(typeof a==q){if(Array.isArray(a)){this.ka(a,b);return}if(a instanceof String||a instanceof Number||a instanceof Boolean)a=a.valueOf();else{this.ma(a,b);return}}switch(typeof a){case r:this.aa(a,b);break;case "number":this.la(a,b);break;case "boolean":b.push(String(a));break;case p:b.push("null");break;default:throw Error("Unknown type: "+typeof a);}}};
var da={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\v":"\\u000b"},ea=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g;R.prototype.aa=function(a,b){b.push('"',a.replace(ea,function(c){var d=da[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).slice(1),da[c]=d);return d}),'"')};R.prototype.la=function(a,b){b.push(isFinite(a)&&!isNaN(a)?String(a):"null")};
R.prototype.ka=function(a,b){var c=a.length;b.push("[");for(var d="",e=0;e<c;e++)b.push(d),d=a[e],this.O(this.K?this.K.call(a,String(e),d):d,b),d=",";b.push("]")};R.prototype.ma=function(a,b){b.push("{");var c="",d;for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)){var e=a[d];typeof e!=p&&(b.push(c),this.aa(d,b),b.push(":"),this.O(this.K?this.K.call(a,d,e):e,b),c=",")}b.push("}")};var fa=function(a){if(a.B&&typeof a.B==p)return a.B();if(typeof Map!=="undefined"&&a instanceof Map||typeof Set!=="undefined"&&a instanceof Set)return Array.from(a.values());if(typeof a===r)return a.split("");if(D(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}b=[];c=0;for(d in a)b[c++]=a[d];return b},ha=function(a){if(a.L&&typeof a.L==p)return a.L();if(!a.B||typeof a.B!=p){if(typeof Map!=="undefined"&&a instanceof Map)return Array.from(a.keys());if(!(typeof Set!=="undefined"&&a instanceof
Set)){if(D(a)||typeof a===r){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}b=[];c=0;for(var d in a)b[c++]=d;return b}}},ia=function(a,b,c){if(a.forEach&&typeof a.forEach==p)a.forEach(b,c);else if(D(a)||typeof a===r)Array.prototype.forEach.call(a,b,c);else for(var d=ha(a),e=fa(a),h=e.length,m=0;m<h;m++)b.call(c,e[m],d&&d[m],a)};var ja=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function ka(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var h=a[c].substring(0,d);e=a[c].substring(d+1)}else h=a[c];b(h,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};function S(a,b){this.G=this.J=this.A="";this.F=null;this.H=this.N="";this.j=this.ia=!1;var c;a instanceof S?(this.j=b!==void 0?b:a.j,this.V(a.A),this.W(a.J),this.P(a.G),this.T(a.F),this.setPath(a.getPath()),this.U(a.l.clone()),this.R(a.H)):a&&(c=String(a).match(ja))?(this.j=!!b,this.V(c[1]||"",!0),this.W(c[2]||"",!0),this.P(c[3]||"",!0),this.T(c[4]),this.setPath(c[5]||"",!0),this.U(c[6]||"",!0),this.R(c[7]||"",!0)):(this.j=!!b,this.l=new T(null,this.j))}t=S.prototype;
t.toString=function(){var a=[],b=this.A;b&&a.push(U(b,la,!0),":");var c=this.G;if(c||b=="file")a.push("//"),(b=this.J)&&a.push(U(b,la,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.F,c!=null&&a.push(":",String(c));if(c=this.getPath())this.M()&&c.charAt(0)!="/"&&a.push("/"),a.push(U(c,c.charAt(0)=="/"?ma:na,!0));(c=this.Y())&&a.push("?",c);(c=this.H)&&a.push("#",U(c,oa));return a.join("")};
t.resolve=function(a){var b=this.clone(),c=a.ga();c?b.V(a.A):c=a.ha();c?b.W(a.J):c=a.M();c?b.P(a.G):c=a.ea();var d=a.getPath();if(c)b.T(a.F);else if(c=a.Z()){if(d.charAt(0)!="/")if(this.M()&&!this.Z())d="/"+d;else{var e=b.getPath().lastIndexOf("/");e!=-1&&(d=b.getPath().slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var h=[],m=0;m<e.length;){var f=e[m++];f=="."?d&&m==e.length&&h.push(""):f==".."?((h.length>
1||h.length==1&&h[0]!="")&&h.pop(),d&&m==e.length&&h.push("")):(h.push(f),d=!0)}d=h.join("/")}else d=e}c?b.setPath(d):c=a.fa();c?b.U(a.l.clone()):c=a.da();c&&b.R(a.H);return b};t.clone=function(){return new S(this)};t.V=function(a,b){this.m();if(this.A=b?V(a,!0):a)this.A=this.A.replace(/:$/,"");return this};t.ga=function(){return!!this.A};t.W=function(a,b){this.m();this.J=b?V(a):a;return this};t.ha=function(){return!!this.J};t.P=function(a,b){this.m();this.G=b?V(a,!0):a;return this};t.M=function(){return!!this.G};
t.T=function(a){this.m();if(a){a=Number(a);if(isNaN(a)||a<0)throw Error("Bad port number "+a);this.F=a}else this.F=null;return this};t.ea=function(){return this.F!=null};t.getPath=function(){return this.N};t.setPath=function(a,b){this.m();this.N=b?V(a,!0):a;return this};t.Z=function(){return!!this.N};t.fa=function(){return this.l.toString()!==""};t.U=function(a,b){this.m();a instanceof T?(this.l=a,this.l.S(this.j)):(b||(a=U(a,pa)),this.l=new T(a,this.j));return this};t.Y=function(){return this.l.toString()};
t.getQuery=function(){return this.Y()};t.na=function(a,b){this.m();this.l.set(a,b);return this};t.ca=function(a){return this.l.get(a)};t.R=function(a,b){this.m();this.H=b?V(a):a;return this};t.da=function(){return!!this.H};t.removeParameter=function(a){this.m();this.l.remove(a);return this};t.m=function(){if(this.ia)throw Error("Tried to modify a read-only Uri");};t.S=function(a){this.j=a;this.l&&this.l.S(a);return this};
var V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},U=function(a,b,c){return typeof a===r?(a=encodeURI(a).replace(b,qa),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},qa=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},la=/[#\/\?@]/g,na=/[#\?:]/g,ma=/[#\?]/g,pa=/[#\?@]/g,oa=/#/g,T=function(a,b){this.i=this.h=null;this.v=a||null;this.j=!!b};t=T.prototype;
t.o=function(){if(!this.h&&(this.h=new Map,this.i=0,this.v)){var a=this;ka(this.v,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};t.add=function(a,b){this.o();this.D();a=this.C(a);var c=this.h.get(a);c||this.h.set(a,c=[]);c.push(b);this.i+=1;return this};t.remove=function(a){this.o();a=this.C(a);return this.h.has(a)?(this.D(),this.i-=this.h.get(a).length,this.h.delete(a)):!1};t.clear=function(){this.D();this.h=null;this.i=0};t.isEmpty=function(){this.o();return this.i==0};
t.X=function(a){this.o();a=this.C(a);return this.h.has(a)};t.forEach=function(a,b){this.o();this.h.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};t.L=function(){this.o();for(var a=Array.from(this.h.values()),b=Array.from(this.h.keys()),c=[],d=0;d<b.length;d++)for(var e=a[d],h=0;h<e.length;h++)c.push(b[d]);return c};
t.B=function(a){this.o();var b=[];if(typeof a===r)this.X(a)&&(b=b.concat(this.h.get(this.C(a))));else{a=Array.from(this.h.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};t.set=function(a,b){this.o();this.D();a=this.C(a);this.X(a)&&(this.i-=this.h.get(a).length);this.h.set(a,[b]);this.i+=1;return this};t.get=function(a,b){if(!a)return b;a=this.B(a);return a.length>0?String(a[0]):b};
t.setValues=function(a,b){this.remove(a);if(b.length>0){this.D();var c=this.h,d=c.set;a=this.C(a);var e=b.length;if(e>0){for(var h=Array(e),m=0;m<e;m++)h[m]=b[m];e=h}else e=[];d.call(c,a,e);this.i+=b.length}};
t.toString=function(){if(this.v)return this.v;if(!this.h)return"";for(var a=[],b=Array.from(this.h.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.B(d);for(var h=0;h<d.length;h++){var m=e;d[h]!==""&&(m+="="+encodeURIComponent(String(d[h])));a.push(m)}}return this.v=a.join("&")};t.D=function(){this.v=null};t.clone=function(){var a=new T;a.v=this.v;this.h&&(a.h=new Map(this.h),a.i=this.i);return a};t.C=function(a){a=String(a);this.j&&(a=a.toLowerCase());return a};
t.S=function(a){a&&!this.j&&(this.o(),this.D(),this.h.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,b))},this));this.j=a};t.extend=function(a){for(var b=0;b<arguments.length;b++)ia(arguments[b],function(c,d){this.add(d,c)},this)};function ra(a,b,c){a:{var d=b.nodeType==9?b:b.ownerDocument||b.document;if(d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(b,null))){d=d[a]||d.getPropertyValue(a)||"";break a}d=""}d=d||(b.currentStyle?b.currentStyle[a]:null)||b.style&&b.style[a];return d==null||d=="inherit"||d=="transparent"||d=="rgba(0, 0, 0, 0)"?b!=(b.nodeType==9?b:b.ownerDocument||b.document).body&&b.parentNode?W(a,b.parentNode):c:d}function W(a,b){return ra(a,b,"rgb(0, 0, 0)")}
function sa(){for(var a=Q(document,"IFRAME","blogger-iframe-colorize",void 0),b=0;b<a.length;b++){var c=a[b],d=P(document,c.id+"-src"),e=d.href;if(!(new S(e)).ca("skin")){var h=W("color",c),m=W("backgroundColor",c),f=ra("fontFamily",c,"serif");d.href="https://www.blogger.com/unvisited-link-"+(new Date).valueOf();var g=W("color",d);d=d.href=e;e=encodeURIComponent;h=(new R(void 0)).ja({color:h,backgroundColor:m,unvisitedLinkColor:g,fontFamily:f});e=d+("#"+e(h))}c.src=e}};var ta=!ca&&!(N("Safari")&&!((O()?M("Chromium"):(N("Chrome")||N("CriOS"))&&(O()||!N("Edge"))||N("Silk"))||(O()?0:N("Coast"))||(O()?0:N("Opera"))||(O()?0:N("Edge"))||(O()?M("Microsoft Edge"):N("Edg/"))||(O()?M("Opera"):N("OPR"))||N("Firefox")||N("FxiOS")||N("Silk")||N("Android")));var ua=-1,va=/\.(blogger|google)\.com($|:)/;for(var wa=function(){ua=Math.floor(Math.random()*1E7);for(var a=Q(document,"iframe","blogger-comment-from-post",void 0),b=0;b<a.length;b++){var c=P(document,a[b].id+"-src"),d=new S(c.href);d.na("blogspotRpcToken",ua);c.href=d.toString()}sa();a=function(e){if(va.test(e.origin)&&typeof e.data===r&&e.data.indexOf("set-comment-editor-height")==0){var h=document.getElementById("comment-editor");h.height=e.data.substring(26);if(ta&&h.dataset)h.dataset.resized=!0;else{if(/-[a-z]/.test("resized"))throw Error("");
h.setAttribute("data-"+"resized".replace(/([A-Z])/g,"-$1").toLowerCase(),!0)}}};window.addEventListener?window.addEventListener("message",a,!1):window.attachEvent&&window.attachEvent("onmessage",a)},X=["BLOG_CMT_createIframe"],Y=C,Z;X.length&&(Z=X.shift());)X.length||wa===void 0?Y=Y[Z]&&Y[Z]!==Object.prototype[Z]?Y[Z]:Y[Z]={}:Y[Z]=wa;}).call(this);
